name: Build and push Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 16 * * 5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: limonchoms/nextcloud
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.0.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: limonchoms/nextcloud:latest
